### ISSUE TITLE
talisker with latest gunicorn doesn't support umask '0'

### ISSUE THREAD

**Issue by ricardokirkner** [canonical-ols/talisker#103]
When running talisker 0.9.5 with gunicorn 19.7.1 and passing

--umask=0

I get the following error

talisker.gunicorn: error: argument -m/--umask: invalid auto_int value: '0'

**Comment by bloodearnest** [comment]
Do you also get his error with plain gunicorn?

**Comment by ricardokirkner** [comment]
mhh.. apparently I do, which conflicts with gunicorn's docs... maybe a bug in gunicorn itself?

**Comment by bloodearnest** [comment]
Yes, I think so. talisker.gunicorn simply calls gunicorn's main run method,
it doesn't alter or parse sys.argv at all

**Comment by ricardokirkner** [comment]
Confirmed gunicorn 19.7.1 has this bug and 19.7.0 doesn't, so not really a talisker issue.
