### ISSUE TITLE
/_status/check requires version-info.txt

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/talisker#194]
I expected the `/_status_check` endpoint to work regardless of whether the `version-info.txt` file existed or not (same as `/_status/ping`). But it doesn't seem to - e.g. see https://cn.ubuntu.com/_status/check vs https://snapcraft.io/_status/check.

**Comment by bloodearnest** [comment]
Hmm, so /_status/check should always be available, and simply return 'unknown' if it cannot detect the version.

I think maybe the issue here is with your nginx config.

Firstly, /_status/check is redirecting to /_status/check/, which is not something talisker does.

Secondly, the response from /_status/check/ is generated by nginx, not gunicorn.

    $ curl -v  https://cn.ubuntu.com/_status/check/
    *   Trying 162.213.33.141...
    * Connected to cn.ubuntu.com (162.213.33.141) port 443 (#0)
    * found 148 certificates in /etc/ssl/certs/ca-certificates.crt
    * found 597 certificates in /etc/ssl/certs
    * ALPN, offering http/1.1
    * SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
    *        server certificate verification OK
    *        server certificate status verification SKIPPED
    *        common name: cn.ubuntu.com (matched)
    *        server certificate expiration date OK
    *        server certificate activation date OK
    *        certificate public key: RSA
    *        certificate version: #3
    *        subject: C=GB,L=London,O=Canonical Group Ltd,OU=IS,CN=cn.ubuntu.com
    *        start date: Tue, 20 Mar 2018 00:00:00 GMT
    *        expire date: Wed, 27 Mar 2019 12:00:00 GMT
    *        issuer: C=US,O=DigiCert Inc,CN=DigiCert SHA2 Secure Server CA
    *        compression: NULL
    * ALPN, server accepted to use http/1.1
    > GET /_status/check/ HTTP/1.1
    > Host: cn.ubuntu.com
    > User-Agent: curl/7.47.0
    > Accept: */*
    > 
    < HTTP/1.1 404 NOT FOUND
    < Server: nginx/1.13.5
    < Date: Tue, 03 Apr 2018 12:21:19 GMT
    < Content-Type: text/plain; charset=utf-8
    < Content-Length: 0
    < Connection: keep-alive
    < X-Request-Id: e6c90e59-dac0-4ab8-817e-06f0ee5f19cb
    < Strict-Transport-Security: max-age=15724800; includeSubDomains;
    < 
    * Connection #0 to host cn.ubuntu.com left intact

**Comment by nottrobin** [comment]
> the response from /_status/check/ is generated by nginx, not gunicorn.

The nginx thing is a red herring - this is just because everything in Kubernetes is proxied through the nginx ingress controller. If you `curl -v https://snapcraft.io/_status/check` you'll also see it says it's nginx, but that definitely shows the Talisker status check page.

> I think maybe the issue here is with your nginx config.

There is nothing specific configured *before* Talisker to do any redirecting. The fact that we're seeing the redirect from `/_status/check` -> `/_status/check/` is because the app that serves the site is configured to redirect all non-slash routes to add a slash:

``` bash
$ curl -sI https://cn.ubuntu.com/nothing | grep Location
Location: http://cn.ubuntu.com/nothing/
```

Although this makes me think this may very well be the problem - because it redirects everything, it also redirects `/_status/check`, which might lead to Talisker thinking that we've implemented the `/_status/check` route, even though we haven't - and so it passes through to the application? Is that what's going on? That makes sense.

I can't see how Talisker could do anything more sensible here, I'll close this now.
