### ISSUE TITLE
Ability to provide version-info.txt as environment variable?

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/talisker#195]
It's useful to have the COMMIT_ID available to our application, and the best way for us to provide it is as an environment variable. But talisker reads it from the `version-info.txt` file instead. Would it be possible for talisker to pick it up from *either* the file *or* an environment variable? Just to save us having to [export it in 2 different ways](https://github.com/canonical-websites/snapcraft.io/blob/master/Dockerfile#L15).

**Comment by bloodearnest** [comment]
Good idea.

I'd like to keep all the Talisker related env vars prefixed with TALISKER_, would TALISKER_VERSION work for you?
