### ISSUE TITLE
Could /_status/{missing-page} pass through to the application instead of showing a body-less 404 page?

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/talisker#196]
While investigating https://github.com/canonical-ols/talisker/issues/194, I noticed that https://cn.ubuntu.com/_status/check/ leads to a page that looks (in Chromium/Chrome) very much like a "connection failed" type error:

![image](https://user-images.githubusercontent.com/519935/38280447-3370933c-379d-11e8-9a87-49bb3261ae6f.png)

Although on closer inspection it is in fact a "404" response with an empty body.

The same is true of any unrecognised route under `/_status`.

Would it be possible to simply pass these unrecognised routes through to the application so that they show the normal application 404 page?

**Comment by bloodearnest** [comment]
So I think there are two issues here - dealing with trailing slashes (which is what I think caused /_status/check/ to 404), and passing through to the app, which does make sense, especially in a html/css delivering web app. Will do.

**Comment by bloodearnest** [comment]
Fixed in #212
