### ISSUE TITLE
API changes for the logger in Flask 1.0.0+

### ISSUE THREAD

**Issue by tbille** [canonical-ols/talisker#208]
When upgrading to FLASK v1.0.0+ I get this error:

```bash
Traceback (most recent call last):
  File "PATH/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "PATH/app.py", line 40, in <module>
    talisker.flask.register(app)
  File "PATH/lib/python3.6/site-packages/talisker/flask.py", line 62, in register
    app._logger = logging.getLogger(app.logger_name)
AttributeError: 'Flask' object has no attribute 'logger_name'
```

From [changelog](http://flask.pocoo.org/docs/1.0/changelog/):
> Flask.logger has been simplified. LOGGER_NAME and LOGGER_HANDLER_POLICY config was removed. The logger is always named flask.app. The level is only set on first access, it doesn’t check Flask.debug each time. Only one format is used, not different ones depending on Flask.debug. No handlers are removed, and a handler is only added if no handlers are already configured.

**Comment by bloodearnest** [comment]
Thanks for the report. I saw a CI failure over the weekend for Flask 1.0, but havn't had time to dig into it. Looks like a simple fix.
