### ISSUE TITLE
Missing metrics with multiple workers

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-ols/talisker#238]
On Ubuntu 16.04 LTS, when running talisker 0.9.10 (reproduced in 0.9.9 too) with multiple workers `talisker -w 2` the `/status/_metrics` endpoint is empty

**Comment by sparkiegeek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Figure out talisker vs. prometheus_client + multiprocesses regression](https://trello.com/c/OEefufrE/132-figure-out-talisker-vs-prometheusclient-multiprocesses-regression)

**Comment by bloodearnest** [comment]
Fixed in #240
