### ISSUE TITLE
Version 0.9.14 from pip doesn't seem to be latest

### ISSUE THREAD

**Issue by bartaz** [canonical-ols/talisker#294]
Installing latest version from pip (0.9.14) doesn't seem to solve stats import error: `ImportError: cannot import name 'StatsClientBase'`.

It seems that 0.9.14 released to pip is different from latest 0.9.14 tag in GitHub.

This was found while debugging https://github.com/canonical-websites/snapcraft.io/issues/1042

**Comment by bloodearnest** [comment]
Ah, the tag might be wrong, will fix it. 

Indeed, 0.9.14 was released before the statsd fix landed. You'll need to stick to statsd less than <3.3 until the next release, which should be some time this week, as we found another issue too.
