### ISSUE TITLE
Remove werkzeug as a dependency

### ISSUE THREAD

**Issue by bloodearnest** [canonical-ols/talisker#445]
We used werkzeug for WSGI responses and for local thread/greenlet context, but it would be good to remove it. This would mean some simple WSGI boilerplate for endpoints, but also need a replacement for the local context.

The obvious choice for this is the new stdlib contextvars, (with pre 3.7 backport), so we should see if that would enable dropping werkzeug

**Comment by bloodearnest** [comment]
I had a look at this, and while we don't use werkzeug.local any more, we do still use it for a bunch of wsgi/http stuff that's non-trivial, like content negotiation, so we'd need to implement that ourselves if we want to remove it

**Comment by jugmac00** [comment]
Simon left and I do not see a clear argument for removing werkzeug. Let's close this issue.
