### ISSUE TITLE
How prometheus is supposed to collect metrics from celery?

### ISSUE THREAD

**Issue by IrSent** [canonical-ols/talisker#457]

**Comment by bloodearnest** [comment]
You need to setup a push gateway and manually push them: 

https://github.com/prometheus/client_python#exporting-to-a-pushgateway

This is up to the app and not something I think Talisker can really help with.

But be aware that push gateways introduce their own issues. FWIW, we just currently use statsd for celery metrics, as that is a native push model.

**Comment by IrSent** [comment]
How about making simple server with metrics and spawn a thread in `run_celery()` (https://github.com/canonical-ols/talisker/blob/master/talisker/__init__.py#L213)?
