### ISSUE TITLE
Alternative bind address for status endpoints

### ISSUE THREAD

**Issue by abeluck** [canonical-ols/talisker#467]
Would it be possible with gunicorn to have the `/_status` endpoints exposed over a different `interface:port` than the primary one?

Our use case is that we run an internal network where metrics are exposed separate from the primary one that user traffic is served off of.

**Comment by bloodearnest** [comment]
Hi abeluck

Good question, that's a valid use case.

I think this should be fairly straight forward to support in a simple way. Gunicorn supports binding to multiple interfaces, so we could add a config specifying a private interface, and `/_status` endpoints are restricted to that interface. It'd be all or nothing approach, but a simple implementation, which is always good.

Would that suit your needs?

**Comment by abeluck** [comment]
>Gunicorn supports binding to multiple interfaces, so we could add a config specifying a private interface, and /_status endpoints are restricted to that interface. It'd be all or nothing approach, but a simple implementation, which is always good.

Precisely, only the `/_status` endpoints are necessary.

> Would that suit your needs?
It definitely would!
