### ISSUE TITLE
docs have not been built for more than a year

### ISSUE THREAD

**Issue by jugmac00** [canonical-ols/talisker#596]
see https://readthedocs.org/projects/talisker/

It looks like @bloodearnest is the only maintainer on rtd.

If you do not have the time to fix the rtd setup, could you please add another maintainer? Maybe someone of the regular contributors here? I would also volunteer to do so. I am an employee of Canonical. I work in the Launchpad team, which is a heavy user of talisker.
https://readthedocs.org/profiles/jugmac00/

**Comment by bloodearnest** [comment]
Confirmed with @cjwatson and invite sent!

**Comment by jugmac00** [comment]
Thanks!

Currently, we build documentation for three [versions](https://readthedocs.org/projects/talisker/versions/):
- master
- latest
- stable

I have triggered a manual build for `lastest` to get at least rid of the red / broken docs badge on our readme.

I would suggest to remove (deactivate) the master version, as it is the same as latest anyway, and by removing it, it is one thing less to take care of. I have grepped the code base - there is no link to the master version of the documentation. As I just start with this project, I did not want to do this without asking first.

As of the reason why automatic builds do not work. I cannot see any obvious reasons.

- Maybe automatic builds are deactivated when the last build failed? (we had a failure on `latest` one year ago). I rebuilt latest manually, so maybe this will work again.
- In settings/integrations ( https://readthedocs.org/dashboard/talisker/integrations/76644/ ) I do not see - due to not being a maintainer of the github project - whether there is something wrong. Could you (@bloodearnest) have a look whether all actions are green? And if not, probably do a re-sync.

I will have an eye on documentation building and if it does not get resolved by above actions, I will probably reach out to RTD - they have been very helpful in the past.

**Comment by bloodearnest** [comment]
> Thanks!
> 
> Currently, we build documentation for three [versions](https://readthedocs.org/projects/talisker/versions/):
> 
> * master
> * latest
> * stable
> 
> I have triggered a manual build for `lastest` to get at least rid of the red / broken docs badge on our readme.

I'm like Jacky Weaver - I have no authority here :)

I have removed myself from the RTD maintainers for talisker, as I don't think its my call any more!


> I would suggest to remove (deactivate) the master version, as it is the same as latest anyway, and by removing it, it is one thing less to take care of. I have grepped the code base - there is no link to the master version of the documentation. As I just start with this project, I did not want to do this without asking first.

Makes sense to me.

> As of the reason why automatic builds do not work. I cannot see any obvious reasons.
> 
> * Maybe automatic builds are deactivated when the last build failed? (we had a failure on `latest` one year ago). I rebuilt latest manually, so maybe this will work again.
> * In settings/integrations ( https://readthedocs.org/dashboard/talisker/integrations/76644/ ) I do not see - due to not being a maintainer of the github project - whether there is something wrong. Could you (@bloodearnest) have a look whether all actions are green? And if not, probably do a re-sync.

I attempted a rsync before removing myself. However, I am no longer a maintainer of the github repo either, so I don't think I'll have any more permissions.
 
> I will have an eye on documentation building and if it does not get resolved by above actions, I will probably reach out to RTD - they have been very helpful in the past.

Something changed about the RTD webhooks, and I never quite got to the bottom of it before I left Canonical.

**Comment by jugmac00** [comment]
This has been resolved. @cjwatson kindly granted me the Admin role to this project, so I was able to resync the webhook from the RTD side ( https://readthedocs.org/dashboard/talisker/integrations/ ).
