### ISSUE TITLE
Activate dependabot

### ISSUE THREAD

**Issue by jugmac00** [canonical-ols/talisker#597]
requires.io is no longer and pyup.io has no more free plan.

Let's activate/configure dependabot.

**Comment by verterok** [comment]
@jugmac00 I see it enabled @ https://github.com/canonical-ols/talisker/security/dependabot
Do you want to enable something else? I don't have permissions, but can chase the admins to do it ;-) 

Cheers!

**Comment by jugmac00** [comment]
Seems to work! Thank you!
