### ISSUE TITLE
Adding support for Python 3.12

### ISSUE THREAD

**Issue by goulinkh** [canonical-ols/talisker#606]
The latest LTS version of Ubuntu Noble 24.04 is shipped with Python3 version 3.12.
This package doesn't support 3.12 as importing modules like `talisker.flask` throws a not found module error.

Are there any plans to support this Python3 version?

**Comment by jugmac00** [comment]
@goulinkh we are the maintainers of that package.

**Comment by goulinkh** [comment]
I see! I will take a look into this then, thanks for the info.
