### ISSUE TITLE
Feature request: requests per-request timing metric customisation

### ISSUE THREAD

**Issue by thomir** [canonical-ols/talisker#74]
Talisker will emit a statsd metric for every inter-service HTTP request made with `talisker.requests`. However, the metric name is calculated using the URL used in the request. The issue I'm facing is that we use an internal IP for the remote service rather than a domain name (in this case the target service has no domain name, and we don't want to add one).

Initially I thought that this meant I probably couldn't use talisker's per-request metrics feature. However, I figured I'd open this bug to see if there's a viable workaround.

Perhaps we could have an alternative interface in `talisker.requests` that allows a caller to pass a service name, which talisker could then use instead of the IP address when emitting the metric?

**Comment by bloodearnest** [comment]
Hmm, this is an interesting one.  Agreed that IP address makes no sense as part of the metric name. An application specified name for the upstream does make sense, but I'm not sure the best way to set that.

**Comment by thomir** [comment]
We've worked around this in our services themselves. However, talisker still emits it's per-request metrics. Perhaps as a half-way solution we could have a way to turn those off, since at this point they're just noise...

Cheers :smile:

**Comment by bloodearnest** [comment]
Fixed in #171, released in 0.9.7.

You can now do:

    session.post(..., metric_api_name='api, metric_host_name='myservice')

And the metric name will take these into account.
