### ISSUE TITLE
Talisker 0.9.3 inserts \x1b into log files

### ISSUE THREAD

**Issue by thomir** [canonical-ols/talisker#77]
As it says on the tin. We're running:

talisker 0.9.3
python 3.4.3

deployed on trusty.

We think this was introduced when talisker added automatic colouration when stderr is a tty. Perhaps for some reason talisker thinks an upstart-owned stderr is a tty, and so applies coloration to it's log output?

**Comment by thomir** [comment]
Upon further consideration, I think we'll work around this by using talisker's log-to-file functionality, rather than relying on upstart's log facilities. However, this will be an issue for anyone upgrading to newer talisker versions still on upstart.

**Comment by thomir** [comment]
...hmmm, except that doesn't appear to be an option for the 'talisker.celery' runner.

**Comment by thomir** [comment]
For now we're working around this by appending `2>&1 | cat` to our upstart job configs.

**Comment by bloodearnest** [comment]
Sorry just saw this. 

Gosh, if systemd-provided stderr is a tty, that breaks many things.

Can you paste/attach your unit file?

**Comment by bloodearnest** [comment]
man systemd.exec suggests StandardError=tty will do just that, sure that's not been set somewhere?

**Comment by bloodearnest** [comment]
Or StandardOutput=tty and StandardError=inherit

**Comment by bloodearnest** [comment]
Ah, I just realised it's upstart, not systemd, sorry.

**Comment by bloodearnest** [comment]
Can you paste your upstart job?

**Comment by bloodearnest** [comment]
So, have rethought this whole think, and the linked PR takes a more conservative approach with avoids the problem. It also incorporates your TALISKER_NO_COLOR change, too, as that is a good idea anyway.
