### ISSUE TITLE
Sentry integration in talisker 0.9.3 does not catch exceptions from views

### ISSUE THREAD

**Issue by thomir** [canonical-ols/talisker#78]
Uncaught exceptions from the `/_status/test/sentry` endpoint, and uncaught exceptions when loading the application are correctly reported. However, uncaught exceptions from flask views are not reported, making the sentry integration not terribly useful.

My test view is this:

```python
def breaks():
    raise Exception("This should be reported")
```

Hitting this view with `curl` results in a 500 response, but no report in sentry.

**Comment by thomir** [comment]
In case it's relevant, the modules we're running are:

```
acceptable==0.7
click==6.7
contextlib2==0.5.4
cookies==2.2.1
Flask==0.12
future==0.16.0
gunicorn==19.7.1
ipaddress==1.0.18
itsdangerous==0.24
Jinja2==2.9.5
jsonschema==2.5.1
MarkupSafe==1.0
pkg-resources==0.0.0
raven==6.0.0
requests==2.13.0
responses==0.5.1
six==1.10.0
snapstore-common==0.0.1
snapstore-schemas==0.15
statsd==3.2.1
talisker==0.9.1
Werkzeug==0.12.1
```

**Comment by bloodearnest** [comment]
Just checked, and it works for me.

How is the flask app configured? Does it follow http://talisker.readthedocs.io/en/latest/flask.html

**Comment by bloodearnest** [comment]
Knowing the affected code, I'm pretty sure we were just missing the register step, which I have gone and done in the affected projects, so I will close this. Feel free to reopen if needed.
