### ISSUE TITLE
Feature request: A testable sentry client

### ISSUE THREAD

**Issue by thomir** [canonical-ols/talisker#83]
It would be nice if we could have some way to assert that a sentry report was sent within a test. Perhaps an interface similar to that provided by the talisker.statsd client could work? Ideally we'd be able to assert on the contents of the report as well.

**Comment by bloodearnest** [comment]
I have the mechanisms for this already in the talisker test suite, basically involves creating a dummy transport that just captures messages to a buffer. It would be good to ship that with talisker itself, as part of a set of test helpers, as previously discussed.

**Comment by squidsoup** [comment]
Hi Simon, I'd just like to leave a +1, as would have found this very useful while working on a new service recently.

**Comment by bloodearnest** [comment]
This is old, but added a talisker.testing.TestContext a while back, which provides this amongst other things
