### ISSUE TITLE
Support PyPy

### ISSUE THREAD

**Issue by bloodearnest** [canonical-ols/talisker#84]
We used to support pypy, but the introduction of psycopg2 support causes issues, so we have removed it.

We should be able to leverage psycopg2cffi as a drop in, but managing the intstall_requires needs some care. Also, the pytest-postgresql test plugin we use doesn't support using psycopg2cffi, so we'd need to fork/upstream a change that allows it to depend on/use pyscopg2cffi on pypy.

**Comment by jugmac00** [comment]
I do not think supporting pypy is any more a valid requirement. If so, please re-open the issue.
