### ISSUE TITLE
Multiline messages overflow into traceback (grok)

### ISSUE THREAD

**Issue by squidsoup** [canonical-ols/talisker#93]
Multiline log messages appear to overflow into 'traceback' resulting in `status`, `ip` etc. not being logged. This is quite misleading as we often filter out 200 `status` to look for issues.

See: https://logging.ols.canonical.com/app/kibana#/doc/logstash-*/logstash-2017.05.18/talisker?id=AVwdUQf2ZwZISI6xIgcV&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-15m,mode:quick,to:now))

Hopefully addressed by https://github.com/canonical-ols/talisker/issues/87 but worth confirming.

**Comment by bloodearnest** [comment]
Hmm, was there a \n in the query string, perhaps? Talisker should probably strip any '\n' chars from the logmsg before sending

**Comment by squidsoup** [comment]
Not certain, but there are a few similar events with the overflow in Kibana
for other queries. Let me know if I can help with surfacing other
misbehaving ones.
